name: aws-example-workflow

on: workflow_dispatch

jobs: 
  # copies the repository contents to the runner("copy" is the name of the job)
  copy:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: List files
      run: ls -la
  image-push:
    runs-on: ubuntu-latest
    steps:
    #copy code
    - name: checkout
      uses: actions/checkout@v4
    #AWS authentication
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
       aws-region: eu-central-1
       aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
       aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
       aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
