name: aws-example-workflow

on: workflow_dispatch

jobs: 
  # copies the repository contents to the runner("copy" is the name of the job)
  copy:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4
    - name: List files
      run: ls -la
  image-push:
    runs-on: ubuntu-latest
    steps:
    #copy code
    - name: checkout
      uses: actions/checkout@v4
    #AWS authentication
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
       aws-region: eu-central-1
       aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
       aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
       aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
    #Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
    #Build , tag and push (refer push commands in ECR)
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ecr-demo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ecr-demo .    
        docker tag ecr-demo:latest 144130276541.dkr.ecr.eu-central-1.amazonaws.com/ecr-demo:latest
        docker push 144130276541.dkr.ecr.eu-central-1.amazonaws.com/ecr-demo:latest
  lint:
    # lint (check for syntax)
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'
    
      - name: Install Dependencies
        run: npm i
    
      - name: Run ESLint
        run: npm run lint
  unit-test:
    # integrated simple testing using supertest
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'
    
      - name: Install Dependencies
        run: npm i
    
      - name: Run tests
        run: npm run test


    
    
        
  
    
    

